apiVersion: v1
kind: Service
metadata:
  name: membership-service
  namespace: gym-lmf
spec:
  type: ClusterIP
  selector:
    app: membership-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP