services:
  auth-service:
    build:
      context: ../../services/auth-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../../services/auth-service/.env.docker
    depends_on:
      auth-db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  membership-service:
    build:
      context: ../../services/membership-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ../../services/membership-service/.env.docker
    depends_on:
      membership-db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  membership-db:
    image: postgres:15
    env_file:
      - ../../services/membership-service/.env.docker
    ports:
      - "5434:5432"
    volumes:
      - membership_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  auth-db:
    image: postgres:15
    env_file:
      - ../../services/auth-service/.env.docker
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped

volumes:
  auth_db_data:
  membership_db_data:
  redis_data:
  grafana_data: